"""created drivers table

Revision ID: 088964b5ed81
Revises: b861971f8bfa
Create Date: 2025-04-29 00:44:16.600793

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "088964b5ed81"
down_revision: Union[str, None] = "b861971f8bfa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drivers",
        sa.Column("driver_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("number", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("driver_id"),
    )
    op.execute(
        "ALTER TABLE f1_data ALTER COLUMN driver_id TYPE INTEGER USING driver_id::integer;"
    )
    op.create_foreign_key(None, "f1_data", "drivers", ["driver_id"], ["driver_id"])
    op.drop_column("f1_data", "grid")
    op.drop_column("f1_data", "year")
    op.drop_column("f1_data", "constructor_id")
    op.drop_column("f1_data", "race_round")
    op.drop_column("f1_data", "position")
    op.drop_column("f1_data", "laps")
    op.drop_column("f1_data", "circuit_id")
    op.drop_column("f1_data", "last_5")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "f1_data", sa.Column("last_5", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "f1_data",
        sa.Column("circuit_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "f1_data", sa.Column("laps", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "f1_data",
        sa.Column("position", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "f1_data",
        sa.Column("race_round", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "f1_data",
        sa.Column("constructor_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "f1_data", sa.Column("grid", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "f1_data", type_="foreignkey")
    op.alter_column(
        "f1_data",
        "driver_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    op.drop_table("drivers")
    # ### end Alembic commands ###
