"""added fields to markets table

Revision ID: 0a9579773bf7
Revises: 7424b7f8040b
Create Date: 2025-06-01 14:14:20.572997

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0a9579773bf7"
down_revision: Union[str, None] = "7424b7f8040b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("markets", sa.Column("category", sa.String(), nullable=False))
    op.add_column("markets", sa.Column("market_status", sa.Integer(), nullable=False))
    op.add_column(
        "markets",
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
    )
    op.add_column("markets", sa.Column("closed_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("markets", "closed_at")
    op.drop_column("markets", "created_at")
    op.drop_column("markets", "market_status")
    op.drop_column("markets", "category")
    # ### end Alembic commands ###
