"""x

Revision ID: 1c16de3dc9e5
Revises: e59003f6190f
Create Date: 2025-04-29 11:46:19.765420

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c16de3dc9e5'
down_revision: Union[str, None] = 'e59003f6190f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('f1_data', sa.Column('last_5', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('f1_data', 'last_5')
    # ### end Alembic commands ###
