"""Created driver and constructor standings table.

Revision ID: 1f89890f9c12
Revises: 463ffd2cf2b8
Create Date: 2025-06-02 23:28:56.428613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f89890f9c12'
down_revision: Union[str, None] = '463ffd2cf2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constructor_standings',
    sa.Column('constructor_standing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('position_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.constructor_id'], ),
    sa.PrimaryKeyConstraint('constructor_standing_id'),
    sa.UniqueConstraint('year', 'round', 'constructor_id', name='uq_constructor_standing')
    )
    op.create_table('driver_standings',
    sa.Column('driver_standing_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('constructor_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('position_text', sa.String(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['constructor_id'], ['constructors.constructor_id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.driver_id'], ),
    sa.PrimaryKeyConstraint('driver_standing_id'),
    sa.UniqueConstraint('year', 'round', 'driver_id', name='uq_driver_standing')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_standings')
    op.drop_table('constructor_standings')
    # ### end Alembic commands ###
