"""Removed given name and family name fields from drivers table.

Revision ID: 286879c55980
Revises: 8cc1dc9654b2
Create Date: 2025-06-02 22:18:15.822912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '286879c55980'
down_revision: Union[str, None] = '8cc1dc9654b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'given_name')
    op.drop_column('drivers', 'family_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('family_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('drivers', sa.Column('given_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
