"""removed notnull constraint on last n races positions

Revision ID: 36ef30420b46
Revises: 6e9dfca52ece
Create Date: 2025-04-27 23:57:30.747112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36ef30420b46'
down_revision: Union[str, None] = '6e9dfca52ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('f1_data', 'last_1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('f1_data', 'last_2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('f1_data', 'last_3',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('f1_data', 'last_4',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('f1_data', 'last_5',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('f1_data', 'last_5',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('f1_data', 'last_4',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('f1_data', 'last_3',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('f1_data', 'last_2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('f1_data', 'last_1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
