"""Added fastest_lap_speed_units field on grand prix results.

Revision ID: 463ffd2cf2b8
Revises: 286879c55980
Create Date: 2025-06-02 22:39:36.087577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '463ffd2cf2b8'
down_revision: Union[str, None] = '286879c55980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grand_prix_results', sa.Column('fastest_lap_speed_unit', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grand_prix_results', 'fastest_lap_speed_unit')
    # ### end Alembic commands ###
