"""Removed position_text from constructor standings.

Revision ID: 660f291052fe
Revises: bd0cee091871
Create Date: 2025-06-03 22:35:02.609274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660f291052fe'
down_revision: Union[str, None] = 'bd0cee091871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('constructor_standings', 'position_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('constructor_standings', sa.Column('position_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
