"""created f1 data table

Revision ID: 6e9dfca52ece
Revises: 
Create Date: 2025-04-27 23:43:02.982979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e9dfca52ece'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('f1_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.String(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('race_round', sa.String(), nullable=False),
    sa.Column('circuit_id', sa.String(), nullable=False),
    sa.Column('constructor_id', sa.String(), nullable=False),
    sa.Column('grid', sa.Integer(), nullable=False),
    sa.Column('laps', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('position_text', sa.String(), nullable=False),
    sa.Column('last_1', sa.String(), nullable=False),
    sa.Column('last_2', sa.String(), nullable=False),
    sa.Column('last_3', sa.String(), nullable=False),
    sa.Column('last_4', sa.String(), nullable=False),
    sa.Column('last_5', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('f1_data')
    # ### end Alembic commands ###
