"""Removed user id foreign key from bets and transactions

Revision ID: 76894b80f760
Revises: b8d776ff8538
Create Date: 2025-06-18 23:08:30.819905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76894b80f760'
down_revision: Union[str, None] = 'b8d776ff8538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('bets_user_id_fkey', 'bets', type_='foreignkey')
    op.drop_column('bets', 'user_id')
    op.drop_constraint('transactions_user_id_fkey', 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('transactions_user_id_fkey', 'transactions', 'users', ['user_id'], ['user_id'])
    op.add_column('bets', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('bets_user_id_fkey', 'bets', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
