"""Created tables for f1 data persistence and pipeline.

Revision ID: 7a4f47e60a20
Revises: e4648bab03ca
Create Date: 2025-06-02 21:19:45.422329

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a4f47e60a20"
down_revision: Union[str, None] = "e4648bab03ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "circuits",
        sa.Column("circuit_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("circuit_ref", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=False),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("circuit_id"),
        sa.UniqueConstraint("circuit_ref"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "constructors",
        sa.Column("constructor_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("constructor_ref", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("nationality", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("constructor_id"),
        sa.UniqueConstraint("constructor_ref"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "grand_prix_results",
        sa.Column(
            "grand_prix_result_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("circuit_id", sa.Integer(), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("constructor_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("position_text", sa.String(), nullable=False),
        sa.Column("points", sa.Float(), nullable=False),
        sa.Column("grid", sa.Integer(), nullable=False),
        sa.Column("laps", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("time_millis", sa.Integer(), nullable=True),
        sa.Column("time_str", sa.String(), nullable=True),
        sa.Column("fastest_lap_rank", sa.Integer(), nullable=True),
        sa.Column("fastest_lap_number", sa.Integer(), nullable=True),
        sa.Column("fastest_lap_time", sa.String(), nullable=True),
        sa.Column("fastest_lap_speed", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["circuit_id"],
            ["circuits.circuit_id"],
        ),
        sa.ForeignKeyConstraint(
            ["constructor_id"],
            ["constructors.constructor_id"],
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.driver_id"],
        ),
        sa.PrimaryKeyConstraint("grand_prix_result_id"),
        sa.UniqueConstraint("year", "round", "driver_id", name="uq_gp_result_driver"),
    )
    op.create_table(
        "quali_results",
        sa.Column("quali_result_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("circuit_id", sa.Integer(), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("constructor_id", sa.Integer(), nullable=False),
        sa.Column("q1", sa.String(), nullable=True),
        sa.Column("q2", sa.String(), nullable=True),
        sa.Column("q3", sa.String(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("position_text", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["circuit_id"],
            ["circuits.circuit_id"],
        ),
        sa.ForeignKeyConstraint(
            ["constructor_id"],
            ["constructors.constructor_id"],
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.driver_id"],
        ),
        sa.PrimaryKeyConstraint("quali_result_id"),
        sa.UniqueConstraint(
            "year", "round", "driver_id", name="uq_quali_result_driver"
        ),
    )
    op.create_table(
        "sprint_results",
        sa.Column("sprint_result_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("round", sa.Integer(), nullable=False),
        sa.Column("circuit_id", sa.Integer(), nullable=False),
        sa.Column("driver_id", sa.Integer(), nullable=False),
        sa.Column("constructor_id", sa.Integer(), nullable=False),
        sa.Column("grid", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("position_text", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["circuit_id"],
            ["circuits.circuit_id"],
        ),
        sa.ForeignKeyConstraint(
            ["constructor_id"],
            ["constructors.constructor_id"],
        ),
        sa.ForeignKeyConstraint(
            ["driver_id"],
            ["drivers.driver_id"],
        ),
        sa.PrimaryKeyConstraint("sprint_result_id"),
        sa.UniqueConstraint(
            "year", "round", "driver_id", name="uq_sprint_result_driver"
        ),
    )
    op.drop_table("f1_data")
    op.add_column("drivers", sa.Column("driver_ref", sa.String(), nullable=False))
    op.add_column("drivers", sa.Column("permanent_number", sa.String(), nullable=False))
    op.add_column("drivers", sa.Column("code", sa.String(), nullable=False))
    op.add_column("drivers", sa.Column("given_name", sa.String(), nullable=False))
    op.add_column("drivers", sa.Column("family_name", sa.String(), nullable=False))
    op.add_column("drivers", sa.Column("dob", sa.Date(), nullable=False))
    op.add_column("drivers", sa.Column("nationality", sa.String(), nullable=False))
    op.create_unique_constraint(None, "drivers", ["driver_ref"])
    op.drop_column("drivers", "name")
    op.drop_column("drivers", "number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "drivers", sa.Column("number", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "drivers", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "drivers", type_="unique")
    op.drop_column("drivers", "nationality")
    op.drop_column("drivers", "dob")
    op.drop_column("drivers", "family_name")
    op.drop_column("drivers", "given_name")
    op.drop_column("drivers", "code")
    op.drop_column("drivers", "permanent_number")
    op.drop_column("drivers", "driver_ref")
    op.create_table(
        "f1_data",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("driver_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("last_1", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("last_2", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("last_3", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("last_4", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("last_5", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["driver_id"], ["drivers.driver_id"], name="f1_data_driver_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="f1_data_pkey"),
        sa.UniqueConstraint("driver_id", name="f1_data_driver_id_key"),
    )
    op.drop_table("sprint_results")
    op.drop_table("quali_results")
    op.drop_table("grand_prix_results")
    op.drop_table("constructors")
    op.drop_table("circuits")
    # ### end Alembic commands ###
