"""Added wins to driver standings table

Revision ID: 8193d3014a23
Revises: 97ec82bb87f0
Create Date: 2025-06-04 17:01:53.327218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8193d3014a23'
down_revision: Union[str, None] = '97ec82bb87f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_standings', sa.Column('wins', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_standings', 'wins')
    # ### end Alembic commands ###
