"""Added year and round columns to markets

Revision ID: 8409d221445a
Revises: 4a5d68eb02b0
Create Date: 2025-06-10 17:44:41.766848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8409d221445a'
down_revision: Union[str, None] = '4a5d68eb02b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('markets', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('markets', sa.Column('round', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('markets', 'round')
    op.drop_column('markets', 'year')
    # ### end Alembic commands ###
