"""added constructor_id field to constructors

Revision ID: 8cc1dc9654b2
Revises: 7a4f47e60a20
Create Date: 2025-06-02 22:15:01.392147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc1dc9654b2'
down_revision: Union[str, None] = '7a4f47e60a20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('constructor_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'drivers', 'constructors', ['constructor_id'], ['constructor_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drivers', type_='foreignkey')
    op.drop_column('drivers', 'constructor_id')
    # ### end Alembic commands ###
