"""Changed bets.created_at to TIMESTAMP WITH TIMEZONE.

Revision ID: 950a23c56d43
Revises: c7e45a701641
Create Date: 2025-06-06 15:02:52.535467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "950a23c56d43"
down_revision: Union[str, None] = "c7e45a701641"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE bets ALTER COLUMN created_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC';"
    )
    op.execute("ALTER TABLE bets ALTER COLUMN created_at SET DEFAULT now();")
    op.execute(
        "ALTER TABLE bets ALTER COLUMN closed_at TYPE TIMESTAMP WITH TIME ZONE USING created_at AT TIME ZONE 'UTC';"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE bets ALTER COLUMN created_at DROP DEFAULT;")
    op.execute(
        "ALTER TABLE bets ALTER COLUMN created_at TYPE TIMESTAMP WITHOUT TIME ZONE USING created_at;"
    )
    op.execute(
        "ALTER TABLE bets ALTER COLUMN closed_at TYPE TIMESTAMP WITHOUT TIME ZONE USING closed_at;"
    )
    # ### end Alembic commands ###
