"""Added appropriate relationships to transactions table.

Revision ID: 994d51e6ce81
Revises: fe27b6e25a1f
Create Date: 2025-06-06 14:24:54.403699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994d51e6ce81'
down_revision: Union[str, None] = 'fe27b6e25a1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'transactions', ['address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='unique')
    # ### end Alembic commands ###
