"""Added created_at to users and settlement amount to bets table.

Revision ID: a56f4ed5661a
Revises: 8193d3014a23
Create Date: 2025-06-05 20:43:11.492244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a56f4ed5661a'
down_revision: Union[str, None] = '8193d3014a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('settle_amount', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created_at')
    op.drop_column('bets', 'settle_amount')
    # ### end Alembic commands ###
