"""added unique race and driver combination constraint

Revision ID: b861971f8bfa
Revises: 36ef30420b46
Create Date: 2025-04-28 00:26:42.684316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b861971f8bfa'
down_revision: Union[str, None] = '36ef30420b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'f1_data', ['race_id', 'driver_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'f1_data', type_='unique')
    # ### end Alembic commands ###
