"""Removed wins and positionText from driver standings.

Revision ID: bd0cee091871
Revises: 1f89890f9c12
Create Date: 2025-06-03 00:24:35.588686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd0cee091871'
down_revision: Union[str, None] = '1f89890f9c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_standings', 'wins')
    op.drop_column('driver_standings', 'position_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_standings', sa.Column('position_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('driver_standings', sa.Column('wins', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
