"""Added settlement_txn field to bets table.

Revision ID: e4648bab03ca
Revises: 0a9579773bf7
Create Date: 2025-06-02 01:38:59.855235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4648bab03ca'
down_revision: Union[str, None] = '0a9579773bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('settlement_txn', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bets', 'settlement_txn')
    # ### end Alembic commands ###
