"""Dropped year, position_text and race id

Revision ID: e59003f6190f
Revises: 088964b5ed81
Create Date: 2025-04-29 09:56:09.356749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59003f6190f'
down_revision: Union[str, None] = '088964b5ed81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('f1_data_race_id_driver_id_key', 'f1_data', type_='unique')
    op.create_unique_constraint(None, 'f1_data', ['driver_id'])
    op.drop_column('f1_data', 'year')
    op.drop_column('f1_data', 'position_text')
    op.drop_column('f1_data', 'race_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('f1_data', sa.Column('race_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('f1_data', sa.Column('position_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('f1_data', sa.Column('year', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'f1_data', type_='unique')
    op.create_unique_constraint('f1_data_race_id_driver_id_key', 'f1_data', ['race_id', 'driver_id'])
    # ### end Alembic commands ###
